 SuperScreen = Instance.new("ScreenGui")
 TopBar = Instance.new("TextLabel")
 UICorner = Instance.new("UICorner")
 Version = Instance.new("TextLabel")
 UICorner_2 = Instance.new("UICorner")
 DestroyUI = Instance.new("TextButton")
 UICorner_3 = Instance.new("UICorner")
 CloseUI = Instance.new("TextButton")
 UICorner_4 = Instance.new("UICorner")
 Check = Instance.new("ImageLabel")
 Barrier = Instance.new("Frame")
 MAIN = Instance.new("Frame")
 UICorner_5 = Instance.new("UICorner")
 Side = Instance.new("Frame")
 UICorner_6 = Instance.new("UICorner")
 Player = Instance.new("TextButton")
 UICorner_7 = Instance.new("UICorner")
 Credits = Instance.new("TextButton")
 UICorner_8 = Instance.new("UICorner")
 Settings = Instance.new("TextButton")
 UICorner_9 = Instance.new("UICorner")
 Combat = Instance.new("TextButton")
 UICorner_10 = Instance.new("UICorner")
 GameMods = Instance.new("TextButton")
 UICorner_11 = Instance.new("UICorner")
 GameScrollingFrames = Instance.new("Frame")
 UICorner_12 = Instance.new("UICorner")
 Player_2 = Instance.new("ScrollingFrame")
 Walkspeed = Instance.new("TextButton")
 OnOff = Instance.new("TextButton")
 UICorner_13 = Instance.new("UICorner")
 Show = Instance.new("TextButton")
 UICorner_14 = Instance.new("UICorner")
 UICorner_15 = Instance.new("UICorner")
 CheckActive = Instance.new("ImageLabel")
 Value = Instance.new("TextBox")
 UICorner_16 = Instance.new("UICorner")
 VelocityWalkspeed = Instance.new("TextButton")
 OnOff_2 = Instance.new("TextButton")
 UICorner_17 = Instance.new("UICorner")
 Show_2 = Instance.new("TextButton")
 UICorner_18 = Instance.new("UICorner")
 UICorner_19 = Instance.new("UICorner")
 CheckActive_2 = Instance.new("ImageLabel")
 Value_2 = Instance.new("TextBox")
 UICorner_20 = Instance.new("UICorner")
 FlyX = Instance.new("TextButton")
 OnOff_3 = Instance.new("TextButton")
 UICorner_21 = Instance.new("UICorner")
 Show_3 = Instance.new("TextButton")
 UICorner_22 = Instance.new("UICorner")
 UICorner_23 = Instance.new("UICorner")
 CheckActive_3 = Instance.new("ImageLabel")
 Noclip = Instance.new("TextButton")
 OnOff_4 = Instance.new("TextButton")
 UICorner_24 = Instance.new("UICorner")
 Show_4 = Instance.new("TextButton")
 UICorner_25 = Instance.new("UICorner")
 UICorner_26 = Instance.new("UICorner")
 CheckActive_4 = Instance.new("ImageLabel")
 RealFly = Instance.new("TextButton")
 OnOff_5 = Instance.new("TextButton")
 UICorner_27 = Instance.new("UICorner")
 Show_5 = Instance.new("TextButton")
 UICorner_28 = Instance.new("UICorner")
 UICorner_29 = Instance.new("UICorner")
 CheckActive_5 = Instance.new("ImageLabel")
 Jump = Instance.new("TextButton")
 OnOff_6 = Instance.new("TextButton")
 UICorner_30 = Instance.new("UICorner")
 Show_6 = Instance.new("TextButton")
 UICorner_31 = Instance.new("UICorner")
 UICorner_32 = Instance.new("UICorner")
 CheckActive_6 = Instance.new("ImageLabel")
 Value_3 = Instance.new("TextBox")
 UICorner_33 = Instance.new("UICorner")
 GameMods_2 = Instance.new("ScrollingFrame")
 TrapAll = Instance.new("TextButton")
 OnOff_7 = Instance.new("TextButton")
 UICorner_34 = Instance.new("UICorner")
 Show_7 = Instance.new("TextButton")
 UICorner_35 = Instance.new("UICorner")
 UICorner_36 = Instance.new("UICorner")
 CheckActive_7 = Instance.new("ImageLabel")
 Godmode = Instance.new("TextButton")
 UICorner_37 = Instance.new("UICorner")
 Removebarriers = Instance.new("TextButton")
 UICorner_38 = Instance.new("UICorner")
 GetGun = Instance.new("TextButton")
 UICorner_39 = Instance.new("UICorner")
 TextLabel = Instance.new("TextLabel")
 Crash = Instance.new("TextButton")
 UICorner_40 = Instance.new("UICorner")
 Imrpovecrahsuc6 = Instance.new("TextButton")
 OnOff_8 = Instance.new("TextButton")
 UICorner_41 = Instance.new("UICorner")
 Show_8 = Instance.new("TextButton")
 UICorner_42 = Instance.new("UICorner")
 UICorner_43 = Instance.new("UICorner")
 CheckActive_8 = Instance.new("ImageLabel")
 DeadC = Instance.new("TextButton")
 OnOff_9 = Instance.new("TextButton")
 UICorner_44 = Instance.new("UICorner")
 Show_9 = Instance.new("TextButton")
 UICorner_45 = Instance.new("UICorner")
 UICorner_46 = Instance.new("UICorner")
 CheckActive_9 = Instance.new("ImageLabel")
 Combat_2 = Instance.new("ScrollingFrame")
 Killall = Instance.new("TextButton")
 UICorner_47 = Instance.new("UICorner")
 Settings_2 = Instance.new("ScrollingFrame")
 Chams = Instance.new("TextButton")
 OnOff_10 = Instance.new("TextButton")
 UICorner_48 = Instance.new("UICorner")
 Show_10 = Instance.new("TextButton")
 UICorner_49 = Instance.new("UICorner")
 UICorner_50 = Instance.new("UICorner")
 CheckActive_10 = Instance.new("ImageLabel")
 ESP = Instance.new("TextButton")
 OnOff_11 = Instance.new("TextButton")
 UICorner_51 = Instance.new("UICorner")
 Show_11 = Instance.new("TextButton")
 UICorner_52 = Instance.new("UICorner")
 UICorner_53 = Instance.new("UICorner")
 CheckActive_11 = Instance.new("ImageLabel")
 Gunesp = Instance.new("TextButton")
 OnOff_12 = Instance.new("TextButton")
 UICorner_54 = Instance.new("UICorner")
 Show_12 = Instance.new("TextButton")
 UICorner_55 = Instance.new("UICorner")
 UICorner_56 = Instance.new("UICorner")
 CheckActive_12 = Instance.new("ImageLabel")
 Xray = Instance.new("TextButton")
 OnOff_13 = Instance.new("TextButton")
 UICorner_57 = Instance.new("UICorner")
 Show_13 = Instance.new("TextButton")
 UICorner_58 = Instance.new("UICorner")
 UICorner_59 = Instance.new("UICorner")
 CheckActive_13 = Instance.new("ImageLabel")
 Credits_2 = Instance.new("ScrollingFrame")
 TV = Instance.new("TextButton")
 UICorner_60 = Instance.new("UICorner")
 Lobbby = Instance.new("TextButton")
 UICorner_61 = Instance.new("UICorner")
 Sheriff = Instance.new("TextButton")
 UICorner_62 = Instance.new("UICorner")
 Murderer = Instance.new("TextButton")
 UICorner_63 = Instance.new("UICorner")
